### PR TITLE
fixes #22, fixes #18

### LINKED ISSUE #18: Add `.champion` to complement `.champion_id`
We have real Champion objects, so let's use them! Calling `.champion` on a game/summoner/etc. should retrieve the full Champion object from the ID.

### LINKED ISSUE #22: Finding a Champion based on its ID.
Sort of a nuisance trying to find out who played what champ in a game because a game is returning the champion's id, not their name. I'm not sure if you already support finding a champion by its id, but here's what I suggest.

def self.champion(lookup_value)
        if lookup_value.is_a? String
                self.all_champions.find {|champ| champ.name == lookup_value}
        else
                self.all_champions.find {|champ| champ.id == lookup_value}
        end
end

P.S. I'm pretty new to all of this stuff so if this was just a waste of time, sorry :(
Edit: I have no clue how to use github's flavored markdown so it looks all bad

### PR DESCRIPTION
**Pull request by imogenkinsman**
- added some unit tests
- added caching for champions
- can now look up champions by id
- added champion methods to game and summoner

### CODE REVIEW

**Comment by PeterBorah** [comment]
Sorry I haven't had time to really look at this in the past couple days. Been traveling/seeing family. I have a few more days off work, and will not be traveling after tomorrow, so I should be able to put some more time into this very soon.

Thanks for continuing to do so much work on this!

**Comment by imogenkinsman** [comment]
No problem (and no rush!), I've been busy with family stuff too. I just got back home, so I'll (hopefully) put more time into this in the next few days.

I'm going to make another commit to this request in a bit.

**Comment by PeterBorah** [comment]
This looks good! I'm going to merge it, but before I release it as a new version of the gem I want to take a stab at coming up with a consistent caching scheme. As it is, there's no good way to grab the newest version of the champion data.

Super minor comment: In the future, would you mind having commit messages that said what they did, rather than just referencing the issue? It'll just make our lives a bit easier in the future as we're looking through the git log and such. Like I said, it's a super minor point, and it looks great otherwise!

**Comment by imogenkinsman** [comment]
Yeah, I was doing that because github links it and the issue that way... but it certainly makes the log hard to read. I think it might work better to make a descriptive commit message in addition to that.

Feel free to leave comments on my commits etc, I'm pretty thick skinned and I haven't done much ruby professionally, so suggestions and criticism are appeciated.

**Comment by PeterBorah** [comment]
Yeah, I think I prefer doing both. Like:

> Find champions by ID (fixes #22)

And yeah, I'll try to do that when I see something. But I think you overestimate how experienced I am. ;) Feel free to make comments on my work too!

**Pull request merged**
