### PR TITLE
Added to masteries; added runes

### PR DESCRIPTION
**Pull request by imogenkinsman**
Are you cool with pull requests? I'd love to work on this.

I added a current_mastery_page instance function to the Summoner class, and saved the mastery_pages result to an instance variable (doesn't make sense to make the API request every time we want it).

### CODE REVIEW

**Comment by imogenkinsman** [comment]
I've added runes.

One thing to note is that when hitting the mastery or runes endpoints, the "talents" and "slots" hash keys (for masteries and runes, respectively) can return nil if that page is empty. I ran into this when testing the runes code, and suspect it affects masteries as well (though I haven't tested it yet).

Runes/masteries can probably be DRY'd a bit - I can take a stab at it later.

Also, whitespace should be stripped from the summoner name string for lookups - it'll break the URI the way it is now.

**Comment by PeterBorah** [comment]
I'll take a look at this tonight. Thanks for the pull request!

**Comment by imogenkinsman** [comment]
Cleaned up mastery_pages and rune_pages a bit - now instead of adding more methods, there's an optional param.

```
summoner = vigor.summoner("semiel")
summoner.mastery_pages :current
```

> saved the mastery_pages result to an instance variable (doesn't make sense to make the API request every time we want it)

I thought about this, and it really depends on how you'd like to design this. Certain information can become stale really quickly, like the current rune/mastery page can change every game. It could make more sense semantically to do a new get request every time that method is called, and let the dev save the response knowing that that info will be "old" from that point on. However, I'd also like to be conservative about the # of API calls we make - there shouldn't be any "gotchas" for people who want to use this gem without knowing how it makes requests, and one might assume that summoner/mastery/rune info just takes one API call when creating the summoner object. I think it's better to assume that all data after creating a new summoner is stale to some degree, since even the data we're using to instantiate that object can change (level, icon).

**Comment by PeterBorah** [comment]
A lot of this looks great. Thanks for doing this! 

I'm not going to merge this tonight, because I want to think/talk to you a bit more about some of the interface design, but I fully intend to merge at least large chunks of it.

I love the idea of a way to directly get the current mastery page, but I'm not entirely sold on the syntax. To me, the plural `mastery_pages` doesn't mesh well with an option that returns anything other than a list. Because of that, I actually liked your original version better. 

One possibility would be a method like `current_mastery_page` or `current_masteries`. Another possibility might be to use your option idea, while renaming the existing method to just `masteries`. (Though I still am nervous about a method that might return a MasteryPage, and might return a list.) I'm sure there are other possibilities I haven't thought of. What are your thoughts?

I'm torn about saving the results of `mastery_pages`, for the same reasons you are. One possibility I kinda like would be to do the caching by default, but allow a `:refresh` option or the like? We're going to run into this problem a lot, so it may be worth thinking about a general strategy for this. (See issue #5).

Thanks again for doing all this. It's nice to not be doing it all by my lonesome!

**Comment by PeterBorah** [comment]
I just merged the whitespace fix, since that's an unambiguously good change. :)

**Comment by PeterBorah** [comment]
I added everything but d3d2e6f, since I liked your old syntax better. I'm going to go ahead and close this pull request, since most of it has been cherry-picked in by now.

Thanks again!

**Comment by PeterBorah** [comment]
Oh, just so you know: I also added a test, and changed some of the field names.

**Comment by imogenkinsman** [comment]
> Thanks again for doing all this. It's nice to not be doing it all by my lonesome!

Yeah, no problem. Coding with someone else is a lot more fun - it's nice to have a sounding board for ideas.

> I love the idea of a way to directly get the current mastery page, but I'm not entirely sold on the syntax. To me, the plural mastery_pages doesn't mesh well with an option that returns anything other than a list. Because of that, I actually liked your original version better.

Agreed, I think the original works better (for now). I was just wary of cluttering up Client with tons of methods.

> I'm torn about saving the results of mastery_pages, for the same reasons you are.

I'll continue this in #5, since this pull request is closed now.

**Pull request closed without merging**
